### ISSUE TITLE
Grinding doesnt progress

### ISSUE THREAD

**Issue by ryan919** [Bjanski/ExAd#41]
Hello i get the option to grind and the animation starts, but it doesnt progress, it just eats up the batteries until none are left, its probably something i have done wrong, could you please maybe tell me where i should look to try rectify the problem.

i do get this in my RPT file 
17:28:07 Scripting function 'exadserver_fnc_clientrequest' is not allowed to be remotely executed

Thanks very much for releasing these add ons :)

**Comment by Bjanski** [comment]
@ryan919  That is the issue, you have missed something in the installation process. 

Double check that you have added all the code from the description.ext file and also make sure you have added the BE filters for remoetExec
