### ISSUE TITLE
Error after installing ExAD Core / xm8 and VG

### ISSUE THREAD

**Issue by Orbitus** [Bjanski/ExAd#48]
Hey there,
i like your script and what it does.
Today i have set up a new server and only wanted to add core/xm8/vg
I did everything according to your guide. After the Installation was complete i got following error in RPT log. 
As soon as i do a rollback bevore the installation of your scripts the server is working perfectly fine.
I hope you can help me!
If any further information is needed, let me know
17:44:57 "ExileServer - Loading families from database..."
17:44:57 "ExileServer - Database Error: Error Unknown Protocol"
17:44:57 Error in expression < to _numberOfClans - 1 do 
{
((_clanIDs select _i) select 0) call ExileServer_sy>
17:44:57   Error position: <select _i) select 0) call ExileServer_sy>
17:44:57   Error Generic error in expression
17:44:57 File exile_server\code\ExileServer_world_loadAllClans.sqf, line 25

**Comment by Bjanski** [comment]
@Orbitus I'll look into on Thursday when I get back home
