### ISSUE TITLE
Can't make Virtual Garage work..

### ISSUE THREAD

**Issue by Micky57** [Bjanski/ExAd#55]
Hi,

I'm trying for 3 days  now to make Virtual Garage work but nothing happened, i followed the tutorial step by step, but no app in xm8..

Can you help me please?

My server is hosted by GTXGaming if it's can help.

P.S: Sorry for my bad English =/.

Thanks for your help.

**Comment by Bjanski** [comment]
This is not right forum to ask for help. Send me an PM on the [Exile forum](http://www.exilemod.com/profile/7143-janski/) and I'll help you :smile:
