### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by Bagback** [Bjanski/ExAd#64]
Get this in game Resource Title ExAd_statusbar not found. Had all the other apps working added this today and that message pops up and in game i have access to the status bar settings but nothing happens. Sorry if its a noob error on my part

**Comment by Bjanski** [comment]
@Bagback 
If you want private help send me a PM on [Exile, Bjanski](http://www.exilemod.com/profile/7143-janski/)
This error have been approached and  treated multiple times in the ExAd thread, e.g. [here](http://www.exilemod.com/topic/13865-exad-package-of-virtual-garagexm8statsbarhalo-parachuteadmin-eventshackinggrindingvehicle-upgrade/?page=57#comment-118408) and [here](http://www.exilemod.com/topic/13865-exad-package-of-virtual-garagexm8statsbarhalo-parachuteadmin-eventshackinggrindingvehicle-upgrade/?page=54#comment-118076)

Please search the thread, found it in less than 1 minute.
