### ISSUE TITLE
Server Info Page

### ISSUE THREAD

**Issue by colonelfury9** [Bjanski/ExAd#67]
Whenever I have the ExAd plugin installed you can no longer use/see the server info page of the XM8, not sure if I messed something up or this is a known bug but would like to see if theres a possible fix or just something on my end. thanks!

**Comment by Bjanski** [comment]
@colonelfury9 this works for me, go through the install instructions again to see if you missed something. 

Is this something that have stopped working since the last exile update?

**Comment by colonelfury9** [comment]
Sorry for not replying, for some reason I didn't get an email notification. But yeah, I went through all the installation instructions again and everything seems to be fine. And sorry for not making it clear, but it is the default server info button that doesn't work, the custom one from the mod works fine. Just need a way to either disable the default one so I don't have two.
