### ISSUE TITLE
grind lock not working

### ISSUE THREAD

**Issue by swiftplague** [Bjanski/ExAd#68]
22:09:18 "Dispatching message 'grindProgress'..."
22:09:18 Error in expression <iable ["ExAd_Grinding_progress", 0]) >= ExAd_GRINDING_OBJECT_MAX)then{
_object s>
22:09:18   Error position: <ExAd_GRINDING_OBJECT_MAX)then{
_object s>
22:09:18   Error Undefined variable in expression: exad_grinding_object_max
22:09:18 File exad_grinding\Functions\fn_grindProgress.sqf, line 25

**Comment by Bjanski** [comment]
You are missing a file or have changed something in the code that you are not supposed to
