### ISSUE TITLE
ExAd on Tanoa

### ISSUE THREAD

**Issue by Shizzo882** [Bjanski/ExAd#69]
hay i have a Question i want to wart you ExAd0.8.2 on Exile taono i have install it with you video but ther server dosn´t work now .... :(

i see in you video you testing the statusbaron tanoa . i  have install Core then  xm8 then VG . dosent work :(

last question where i find you new statsbar? 

thx Kenneth

sorry for my bad englisch i am from germany i hope you can read it

**Comment by Bjanski** [comment]
This is not a bug, ask in the exile forum. Pretty sure someone can help you

**Comment by Shizzo882** [comment]
ok thx i have found ist :) but verry thx for you time :)
