### ISSUE TITLE
Warning Message: No entry 'bin\config.bin/CfgPatches/ExAd_Core.units

### ISSUE THREAD

**Issue by SAYREXx** [Bjanski/ExAd#74]
after installation, zeus throws the error:
` 3:18:20 Warning Message: No entry 'bin\config.bin/CfgPatches/ExAd_Core.units'.
 3:18:20 Warning Message: No entry 'bin\config.bin/CfgPatches/ExAd_Hacking.units'.
 3:18:20 Warning Message: No entry 'bin\config.bin/CfgPatches/ExAd_VG.units'.`

**Comment by Bjanski** [comment]
@SAYREXx disable zues and the issue will disappear.

**Comment by SAYREXx** [comment]
This is not the solution! I need Zeus!

**Comment by Bjanski** [comment]
@SAYREXx  You don't need zeus to play Exile or do you? What does it do for you?

**Comment by SAYREXx** [comment]
@Bjanski Very easy and simple to hold events for the players:) Please Help me:)

**Comment by Bjanski** [comment]
There's a fix for it now in the [zeus_fix branch](https://github.com/Bjanski/ExAd/tree/zeus_fix) haven't tried it but should suppress the error. 

To install just replace the all the ExAd server addons you are using.

**Comment by Bjanski** [comment]
@SAYREXx There's a fix for it now in the [zeus_fix branch](https://github.com/Bjanski/ExAd/tree/zeus_fix) haven't tried it but should suppress the error.

To install just replace the all the ExAd server addons you are using.

**Comment by SAYREXx** [comment]
@Bjanski thank you! Now everything works fine! You are master!))
