### ISSUE TITLE
EXILE MOD

### ISSUE THREAD

**Issue by joboo33** [Bjanski/ExAd#77]
I'm getting this error right before I spawn..

Script ExAdClient\XM8\Apps\CHUD\OnClose.sqf Not Found.

After I hit ok I can't use my map or XM8

**Comment by Gr8z** [comment]
CHUD or CHVD ?

**Comment by joboo33** [comment]
CHVD

**Comment by Gr8z** [comment]
Check if you have that file in your mission PBO on that path or not.

**Comment by Bjanski** [comment]
Most likely wrongly installed
