### ISSUE TITLE
Battleye SR #0

### ISSUE THREAD

**Issue by Kruemmel** [Bjanski/ExAd#78]
I am getting: 
`"r select 3] call ExAd_fnc_prepareSlider;

_sliderR ctrlSetEventHandler ["SliderPosChanged", format["(_this select 0) ctrlSetTool"`

I tried to get rid of it with:
`!="r select 3] call ExAd_fnc_prepareSlider;\n\n_sliderR ctrlSetEventHandler [\"SliderPosChanged\", format[\"(_this select 0) ctrlSetTool"`

But it did not help at all. What can i do against this SR? 

Thanks

**Comment by Bjanski** [comment]
use 
```
!="_sliderR ctrlSetEventHandler [\"SliderPosChanged\", format[\"(_this select 0) ctrlSetTool"
```

**Comment by Bjanski** [comment]
That should solve it.

**Comment by Kruemmel** [comment]
Thank you very much :+1: has helped a much ^^
