### ISSUE TITLE
Vehicles lose ammo types on VG

### ISSUE THREAD

**Issue by Chris-I** [Bjanski/ExAd#80]
A vehicle that has multiple ammo types for the same turret examle (AP, HE shells etc) Will lose the other ammo type but the primary.

How to reproduce:
Store a vehicle that has multiple ammo types for the same gun (AP, HE) and then fetch it back out, Step into gunner seat and you wont have the second ammo type anymore.

**Comment by Bjanski** [comment]
This isn't related to ExAd since I use Exile to load and unload vehicles from the map.
